language: go

rvm: trusty
sudo: required

matrix:
    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/Muckfoot/ImageShare/CI/darwin.sh; fi

script:
    - brew update
    - brew install qt5
    - brew outdated qt5 || brew upgrade qt5
    - ln -s /usr/local/Cellar/qt/5.9.1 $HOME/Desktop/Qt5.9.1

    - sudo chown $USER /usr/local/bin
    - sudo chown $USER $GOROOT/pkg | true

    - df -h
    - diskutil list

    -ls $HOME/*
    -du -sh $HOME/*

    - go get -v github.com/therecipe/qt/cmd/...
    - go get -v github.com/everdev/mack
    - go get -v gopkg.in/mgo.v2
    - $GOPATH/bin/qtsetup
    - go run main.go ui.go utils.go types.go