language: go

rvm: trusty
sudo: required

matrix:
    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

script:
    - go get -v github.com/therecipe/qt/cmd/...
    - if [[ "$DESKTOP" == "true" ]]; then $GOPATH/bin/qtsetup full desktop; fi