language: go

rvm: trusty
sudo: required

matrix:
    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/Muckfoot/ImageShare/CI/darwin.sh; fi

script:
    - go get -v github.com/therecipe/qt/cmd/...
    - go get -v github.com/everdev/mack
    - go get -v gopkg.in/mgo.v2
    - go run main.go ui.go utils.go types.go